import type { Category, Product } from '@/lib/types';
export const categories: { id: Category; name: string; description: string }[] = [
  { id: 'home', name: 'Home & living', description: 'Furniture accents and home goods.' },
  { id: 'accessories', name: 'Accessories', description: 'Bags and personal accessories.' },
  { id: 'essentials', name: 'Everyday essentials', description: 'Stationery and practical goods.' },
];
const photo = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1000&q=85`;
const items: [string, string, Category, number, string, string, string[]][] = [
  [
    'everyday-ceramic-mug',
    'The Everyday Mug',
    'home',
    850,
    'photo-1514228742587-6b1558fcca3d',
    'A 350 ml glazed stoneware mug with a rounded handle. Suitable for the dishwasher and microwave.',
    ['Glazed stoneware · 350 ml', 'Comfortable rounded handle', 'Dishwasher and microwave safe'],
  ],
  [
    'canvas-weekender',
    'Canvas Weekender',
    'accessories',
    3250,
    'photo-1553062407-98eeb64c6a62',
    'A cotton canvas travel bag with a roomy main compartment and adjustable shoulder straps.',
    ['Durable cotton canvas', 'Roomy main compartment', 'Adjustable shoulder straps'],
  ],
  [
    'linen-cushion',
    'Linen Cushion',
    'home',
    1650,
    'photo-1584100936595-c0654b55a2e2',
    'A 45 × 45 cm cushion in a natural linen blend, with a removable cover for easy washing.',
    ['Natural linen blend', '45 × 45 cm', 'Removable cover; gentle wash'],
  ],
  [
    'daily-notebook',
    'Daily Notes',
    'essentials',
    650,
    'photo-1531346878377-a5be20888e57',
    'An A5 notebook with 192 lined pages and a lay-flat binding for comfortable writing.',
    ['192 lined pages', 'A5 format', 'Lay-flat binding'],
  ],
  [
    'stoneware-vase',
    'The Form Vase',
    'home',
    2100,
    'photo-1578500494198-246f612d3b3d',
    'A 22 cm matte ceramic vase for a few stems or a small arrangement.',
    ['Matte ceramic finish', 'Height: 22 cm', 'Wipe clean with a soft cloth'],
  ],
  [
    'scented-candle',
    'Sunday Candle',
    'home',
    1250,
    'photo-1603006905003-be475563bc59',
    'A 200 g soy wax blend candle with warm woody notes and an approximate 35-hour burn time.',
    ['Soy wax blend · 200 g', 'Cotton wick', 'Approx. 35-hour burn time'],
  ],
  [
    'cotton-throw',
    'The Slow Sunday Throw',
    'home',
    2850,
    'photo-1600369672770-985fd30004eb',
    'A 100% cotton throw measuring 130 × 170 cm. Machine wash cold.',
    ['100% cotton', '130 × 170 cm', 'Machine wash cold'],
  ],
  [
    'wooden-serving-board',
    'Gather Serving Board',
    'home',
    1850,
    'photo-1556911220-bff31c812dba',
    'A solid acacia wood serving board measuring 30 × 20 cm. Hand wash and dry after use.',
    ['Solid acacia wood', '30 × 20 cm', 'Hand wash and dry promptly'],
  ],
  [
    'everyday-tote',
    'Market Day Tote',
    'accessories',
    950,
    'photo-1544816155-12df9643f363',
    'A washable heavyweight cotton tote with an internal slip pocket.',
    ['Heavyweight cotton canvas', 'Internal slip pocket', 'Reusable and washable'],
  ],
  [
    'classic-sunglasses',
    'Daylight Sunglasses',
    'accessories',
    1950,
    'photo-1511499767150-a48a237f0083',
    'Lightweight acetate sunglasses with UV400 lenses and a protective pouch.',
    ['UV400 lenses', 'Lightweight acetate frame', 'Protective pouch included'],
  ],
  [
    'minimal-watch',
    'The Hours Watch',
    'accessories',
    4500,
    'photo-1524805444758-089113d48a6d',
    'A 38 mm quartz watch with an adjustable strap and a clean dial.',
    ['Quartz movement', 'Adjustable strap', '38 mm case'],
  ],
  [
    'leather-wallet',
    'Pocket Companion',
    'accessories',
    1850,
    'photo-1627123424574-724758594e93',
    'A slim folded leather wallet with six card slots.',
    ['Genuine leather', 'Six card slots', 'Slim folded profile'],
  ],
  [
    'woven-hat',
    'Weekend Sun Hat',
    'accessories',
    1450,
    'photo-1588850561407-ed78c282e89b',
    'A woven sun hat with an adjustable internal band. Spot clean only.',
    ['Woven natural fibers', 'Adjustable internal band', 'Spot clean only'],
  ],
  [
    'steel-water-bottle',
    'Go Everywhere Bottle',
    'essentials',
    1450,
    'photo-1602143407151-7111542de6e8',
    'A 500 ml stainless steel bottle with double-wall insulation and a leak-resistant lid.',
    ['Stainless steel · 500 ml', 'Double-wall insulation', 'Leak-resistant screw lid'],
  ],
  [
    'desk-lamp',
    'Evening Desk Light',
    'essentials',
    3250,
    'photo-1507473885765-e6ed057f782c',
    'An adjustable desk lamp with a warm LED bulb included.',
    ['Adjustable shade', 'Warm LED bulb included', 'Standard mains plug'],
  ],
  [
    'ceramic-planter',
    'Little Green Planter',
    'essentials',
    1150,
    'photo-1485955900006-10f4d324d411',
    'A glazed ceramic planter measuring 12 cm across. Plant not included.',
    ['Glazed ceramic', '12 cm diameter', 'Plant not included'],
  ],
  [
    'pour-over-set',
    'Morning Pour-Over',
    'essentials',
    2450,
    'photo-1495474472287-4d71bcdd2085',
    'A pour-over set with a 600 ml glass server and reusable filter.',
    ['Glass coffee server', 'Reusable filter', '600 ml capacity'],
  ],
  [
    'travel-journal',
    'Somewhere Journal',
    'essentials',
    750,
    'photo-1455390582262-044cdead277a',
    'A pocket-size journal with 160 blank pages and a durable soft cover.',
    ['160 blank pages', 'Pocket-friendly format', 'Durable soft cover'],
  ],
];
export const sampleProducts: Product[] = items.map(
  ([slug, name, category, price, image, description, details], i) => ({
    id: `00000000-0000-4000-8000-${String(i + 1).padStart(12, '0')}`,
    slug,
    name,
    category,
    price_minor: price * 100,
    description,
    details,
    image_url: photo(image),
    image_alt: name,
    available: true,
    featured: i < 4,
    badge: i === 0 ? 'Bestseller' : i === 1 ? 'Made for everyday' : i === 2 ? 'New arrival' : null,
  }),
);
