import type { Category, Product } from '@/lib/types';
export const categories: { id: Category; name: string; description: string }[] = [
  { id: 'home', name: 'Home & living', description: 'Make room for the little things.' },
  { id: 'accessories', name: 'Accessories', description: 'Good company, wherever you go.' },
  { id: 'essentials', name: 'Everyday essentials', description: 'A little better, every day.' },
];
const photo = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1000&q=85`;
const items: [string, string, Category, number, string, string, string[]][] = [
  [
    'everyday-ceramic-mug',
    'The Everyday Mug',
    'home',
    850,
    'photo-1514228742587-6b1558fcca3d',
    'A slow morning, a warm cup. Our softly glazed ceramic mug makes an everyday ritual feel a little more considered.',
    ['Glazed stoneware · 350 ml', 'Comfortable rounded handle', 'Dishwasher and microwave safe'],
  ],
  [
    'canvas-weekender',
    'Canvas Weekender',
    'accessories',
    3250,
    'photo-1553062407-98eeb64c6a62',
    'Pack light, go far. A dependable canvas bag for a change of scenery and everything in between.',
    ['Durable cotton canvas', 'Roomy main compartment', 'Adjustable shoulder straps'],
  ],
  [
    'linen-cushion',
    'Linen Cushion',
    'home',
    1650,
    'photo-1584100936595-c0654b55a2e2',
    'An easy layer of texture for your favorite corner. Soft natural fabric with a relaxed, lived-in feel.',
    ['Natural linen blend', '45 × 45 cm', 'Removable cover; gentle wash'],
  ],
  [
    'daily-notebook',
    'Daily Notes',
    'essentials',
    650,
    'photo-1531346878377-a5be20888e57',
    'For passing thoughts and bigger ideas. A beautifully simple notebook with plenty of room to begin.',
    ['192 lined pages', 'A5 format', 'Lay-flat binding'],
  ],
  [
    'stoneware-vase',
    'The Form Vase',
    'home',
    2100,
    'photo-1578500494198-246f612d3b3d',
    'A sculptural home for a few stems, or a quiet statement all on its own.',
    ['Matte ceramic finish', 'Height: 22 cm', 'Wipe clean with a soft cloth'],
  ],
  [
    'scented-candle',
    'Sunday Candle',
    'home',
    1250,
    'photo-1603006905003-be475563bc59',
    'Take a breath. Warm woody notes bring a little of the weekend into any day.',
    ['Soy wax blend · 200 g', 'Cotton wick', 'Approx. 35-hour burn time'],
  ],
  [
    'cotton-throw',
    'The Slow Sunday Throw',
    'home',
    2850,
    'photo-1600369672770-985fd30004eb',
    'Something soft to reach for. An understated throw for cooler evenings and unhurried mornings.',
    ['100% cotton', '130 × 170 cm', 'Machine wash cold'],
  ],
  [
    'wooden-serving-board',
    'Gather Serving Board',
    'home',
    1850,
    'photo-1556911220-bff31c812dba',
    'From the first slice to the last conversation, a naturally beautiful place to share something good.',
    ['Solid acacia wood', '30 × 20 cm', 'Hand wash and dry promptly'],
  ],
  [
    'everyday-tote',
    'Market Day Tote',
    'accessories',
    950,
    'photo-1544816155-12df9643f363',
    'Room for your daily essentials and the unexpected little finds along the way.',
    ['Heavyweight cotton canvas', 'Internal slip pocket', 'Reusable and washable'],
  ],
  [
    'classic-sunglasses',
    'Daylight Sunglasses',
    'accessories',
    1950,
    'photo-1511499767150-a48a237f0083',
    'A timeless shape for bright days. Lightweight frames that go with just about everything.',
    ['UV400 lenses', 'Lightweight acetate frame', 'Protective pouch included'],
  ],
  [
    'minimal-watch',
    'The Hours Watch',
    'accessories',
    4500,
    'photo-1524805444758-089113d48a6d',
    'Keep a little perspective on the passing hours with a simple, beautifully balanced dial.',
    ['Quartz movement', 'Adjustable strap', '38 mm case'],
  ],
  [
    'leather-wallet',
    'Pocket Companion',
    'accessories',
    1850,
    'photo-1627123424574-724758594e93',
    'Only what you need, always close at hand. A slim wallet that gets better with time.',
    ['Genuine leather', 'Six card slots', 'Slim folded profile'],
  ],
  [
    'woven-hat',
    'Weekend Sun Hat',
    'accessories',
    1450,
    'photo-1588850561407-ed78c282e89b',
    'Made for taking the scenic route. A relaxed hat for afternoon walks and days outdoors.',
    ['Woven natural fibers', 'Adjustable internal band', 'Spot clean only'],
  ],
  [
    'steel-water-bottle',
    'Go Everywhere Bottle',
    'essentials',
    1450,
    'photo-1602143407151-7111542de6e8',
    'A daily reminder to pause and recharge. Your favorite drink, ready when you are.',
    ['Stainless steel · 500 ml', 'Double-wall insulation', 'Leak-resistant screw lid'],
  ],
  [
    'desk-lamp',
    'Evening Desk Light',
    'essentials',
    3250,
    'photo-1507473885765-e6ed057f782c',
    'A pool of warm light for the pages, projects, and quiet hours that matter.',
    ['Adjustable shade', 'Warm LED bulb included', 'Standard mains plug'],
  ],
  [
    'ceramic-planter',
    'Little Green Planter',
    'essentials',
    1150,
    'photo-1485955900006-10f4d324d411',
    'Give a little green a place to grow. A simple ceramic planter for your desk or windowsill.',
    ['Glazed ceramic', '12 cm diameter', 'Plant not included'],
  ],
  [
    'pour-over-set',
    'Morning Pour-Over',
    'essentials',
    2450,
    'photo-1495474472287-4d71bcdd2085',
    'Good things take a moment. A thoughtful coffee companion for a slower start to the day.',
    ['Glass coffee server', 'Reusable filter', '600 ml capacity'],
  ],
  [
    'travel-journal',
    'Somewhere Journal',
    'essentials',
    750,
    'photo-1455390582262-044cdead277a',
    'A place for the things you notice. Take it on a journey, or just around the corner.',
    ['160 blank pages', 'Pocket-friendly format', 'Durable soft cover'],
  ],
];
export const sampleProducts: Product[] = items.map(
  ([slug, name, category, price, image, description, details], i) => ({
    id: `00000000-0000-4000-8000-${String(i + 1).padStart(12, '0')}`,
    slug,
    name,
    category,
    price_minor: price * 100,
    description,
    details,
    image_url: photo(image),
    image_alt: name,
    available: true,
    featured: i < 4,
    badge: i === 0 ? 'Bestseller' : i === 1 ? 'Made for everyday' : i === 2 ? 'New arrival' : null,
  }),
);
